Change .format to f string on asv/machine.py
airspeed-velocity/asv pull request #1185
Opened 2022-03-20 16:47 UTC by asnramos

xref #1176 #1077 
Change f-strings instead .format() on asv/machine.py

2022-03-20 20:33 UTC, LucyJimenez requested changes
Great job, @asnramos. I leave you just one comment :)

2022-03-20 20:33 UTC, LucyJimenez commented on asv/machine.py
> +            f"No information stored about machine '{machine_name}'. I know about {util.human_list(d.keys()))}."
```suggestion
            f"No information stored about machine '{machine_name}'. I know about {util.human_list(d.keys()))}.")
```

You miss an `)` to close `util.UserError( )`.

2022-03-21 16:12 UTC, datapythonista commented
@asnramos CI is red, one line is longer than the maximum we allow, 99 characters. Can you check and split it in two lines please?

2022-03-21 18:23 UTC, LucyJimenez requested changes

2022-03-21 19:15 UTC, LucyJimenez approved these changes
LGTM! 🚀

2022-03-21 21:02 UTC, merged

2022-03-21 21:02 UTC, datapythonista commented
Thanks @asnramos, really nice